image: node:6
clone:
  depth: full
pipelines:
  default:
    - step:
        script:
          - echo "Thank you for your push."
  branches:
    master:
      - step:
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD